[versions]
agp = "8.13.2"
converterGson = "3.0.0"
firebaseBom = "34.7.0"
glideVersion = "5.0.5"
googleHiltAndroid = "<version>"
hiltAndroid = "2.54"
hiltAndroidCompiler = "2.54"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
navigationFragmentKtx = "2.8.5"
navigationRuntimeKtx = "2.8.5"
navigationCompose = "2.8.5"
contentpager = "1.0.0"
constraintlayout = "2.2.0"
okhttpVersion = "5.3.2"
picasso = "2.71828"
playServicesAds = "23.6.0"
retrofit = "3.0.0"
fragmentKtx = "1.8.9"
navigationFragment = "2.8.5"
media3CommonKtx = "1.5.1"
engageCore = "1.5.11"
roomCommon = "2.8.4"
mediationTestSuite = "3.0.0"
roomKtx = "2.8.4"
firebaseCrashlyticsKtx = "19.4.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version = "2.9.6" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version = "2.9.6" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCommon" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCommon" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
#noinspection SimilarGradleDependency
dagger-hilt-android-vversion = { module = "com.google.dagger:hilt-android", version = "2.57.2" }
#noinspection SimilarGradleDependency
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
github-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
hilt-android = { module = "com.google.dagger:hilt-android", version = "2.57.2" }
#noinspection SimilarGradleDependency
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version = "2.57.2" }
#noinspection SimilarGradleDependency
hilt-android-compiler-vversion = { module = "com.google.dagger:hilt-android-compiler", version = "2.57.2" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version = "24.9.0" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.4.0" }
engage-core = { group = "com.google.android.engage", name = "engage-core", version.ref = "engageCore" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
mediation-test-suite = { group = "com.google.android.ads", name = "mediation-test-suite", version.ref = "mediationTestSuite" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version = "2.8.9" }